ktor:
    application:
        modules:
            - ApplicationKt.module
    deployment:
        port: 8080
cors:
    host: "*"
    schemes: [ "http", "https" ]
storage:
    driver: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/"
#    user: "postgres"
#    password: "postgres"
jwt:
    issuer: "issuer"
    domain: "domain"
    audience: "audience"
    realm: "realm"
    access:
        secret: "ACCESS PHRASE"
        expiresIn: 1800000
    refresh:
        secret: "REFRESH PHRASE"
        expiresIn: 1209600000