name: Build and deploy to VPS
on:
  push:
    branches:
      - main
permissions:
  packages: write
  contents: read
env:
  IMAGE_NAME: app
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            **/.gradle*
            **/gradle-wrapper.properties

      - run:
          ./gradlew build

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          # This changes all uppercase characters to lowercase.
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env

      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.VPS_IP  }}
          username: ${{ vars.VPS_USERNAME}}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "compose.yaml,.env"
          target: ktor-sample

      - name: Set up SSH Key and Deploy my App on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.VPS_IP }}
          username: ${{ vars.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/ktor-sample
            docker compose pull
            docker compose --env-file .env up -d